### ISSUE TITLE
Does Chameleon still support the ArtificeBlizzard mod from version 1.2.0 onwards?

### ISSUE THREAD

**Issue by InconsiderateBox** [ButteryStancakes/Chameleon#3]
Hey, love the new update! But I noticed no mentions of a previous feature found in Chameleon and wanted to know if it was removed.

If I remember correctly, there was a cross-mod compatibility configuration for the ArtificeBlizzard mod that allowed you to change the cavern type when the mod activated and turned Artifice into a snow map. Since 1.2.0, it seems all mentions of this configuration has disappeared, and I'm concerned that compatibility with ArtificeBlizzard was removed. Is this true? Or is there still a way to set the mineshaft to Ice for when Artifice turns snowy?

Thanks for your time, and again, the recent update was absolutely fantastic. Love the ability to customize cavern types for each map; makes the game experience a lot more spicy.

**Comment by ButteryStancakes** [comment]
I removed this feature just because I didn't think there was very much demand for it. I assumed it was just being used to make Artifice ice caves instead of vanilla caves when you had blizzard chance set to Always. (You could do the same thing in the new config just by giving Artifice ice caves directly)

If you specifically desire for Artifice to switch dynamically (guaranteed ice when it's snowy, but use the configured list when it's not snowy), then I suppose let me know. I will patch it back in and release an update for it

**Comment by InconsiderateBox** [comment]
Thank you for answering.

I do want to see the return of Artifice caverns switching dynamically in response to ArtificeBlizzard activating. Apologies if I'm being a bug for requesting more work from you, especially for what seems to be a niche feature, but it's something I'd desire to see again.

**Comment by ButteryStancakes** [comment]
You're fine. It doesn't take much work :)

**Comment by ButteryStancakes** [comment]
This is now supported again as of v1.2.2. Enable the `AutoAdaptSnow` setting
