### ISSUE TITLE
Lighting on ship is bugged out (Not present on version 1.2.2) [Celestial Tint compatibility]

### ISSUE THREAD

**Issue by LimeSkillZ** [ButteryStancakes/Chameleon#8]
On version 1.2.3 and above, the lighting while in ship is bugged. The modpack I used is below, and removing Celestial Tint fixes the issue. In the console, this message is spammed: 

[Error  : Unity Log] Cascade Shadow atlasing has failed, only one directional light can cast shadows at a time

![image](https://github.com/user-attachments/assets/01cf061a-a316-4b93-82c1-62b5899764e9)

Using this modpack (12 mods total):
01937dd6-ead6-e143-4626-ea9dc3288420

**Comment by ButteryStancakes** [comment]
I added a warning to `PlanetPreview` in the mod description for this specific reason:

> Disable this setting if you experience over-exposed lighting on the ship (such as when using [Celestial Tint](https://thunderstore.io/c/lethal-company/p/sfDesat/Celestial_Tint/))

as well as in-game:

> You should disable this if you encounter lighting issues on the ship.

When this was first added as a feature in ButteryFixes, I would automatically toggle it off if Celestial Tint was installed. But since it's a manual config setting in Chameleon, I decided I'd rather just leave it to the player's control
